apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
spec:
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      containers:
      - name: webhook-server
        image: python:3.9-slim
        ports:
        - containerPort: 5000
        command:
        - /bin/sh
        - -c
        - pip install -r /requirements/requirements.txt && python -u /code/webhook-server.py
        volumeMounts:
        - name: webhook-server-code
          mountPath: /code
        - name: webhook-server-requirements
          mountPath: /requirements
        - name: mlops-pipeline
          mountPath: /mlops
        - mountPath: /var/run/secrets/kubeflow/pipelines
          name: volume-kf-pipeline-token
          readOnly: true
        env:
        - name: KF_PIPELINES_SA_TOKEN_PATH
          value: /var/run/secrets/kubeflow/pipelines/token
      volumes:
      - name: volume-kf-pipeline-token
        projected:
          sources:
            - serviceAccountToken:
                path: token
                expirationSeconds: 7200
                audience: pipelines.kubeflow.org 
      - name: mlops-pipeline
        configMap:
          name: mlops-pipeline
      - name: webhook-server-code
        configMap:
          name: webhook-server-code
      - name: webhook-server-requirements
        configMap:
          name: webhook-server-requirements

---

apiVersion: v1
kind: Service
metadata:
  name: webhook-server
spec:
  selector:
    app: webhook-server
  ports:
  - port: 5000
    targetPort: 5000
