{
 "title": "model_monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage predictions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "actual_value", "legendFormat": "Actual CPU usage" },
    { "expr": "predicted_value", "legendFormat": "Predicted CPU usage" }
   ]
  },
  {
   "title": "R2 score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "model_r2_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "R2 Score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_r2_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RMSE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "model_rmse", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RMSE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_rmse", "legendFormat": "__auto" }
   ]
  }
 ]
}