apiVersion: batch/v1
kind: CronJob
metadata:
  name: pinger
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      completions: 2
      parallelism: 2
      successfulJobsHistoryLimit: 0
      template:
        spec:
          containers:
          - name: pinger
            image: nginx
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - apt-get update && apt-get install -y apache2-utils && ab -n 500000 http://nginx.app.svc.cluster.local/
          restartPolicy: OnFailure