name: "Training pipeline CI"

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-training-pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r kubeflow/pipelines/requirements.txt

    - name: Run python code
      env:
        KUBEFLOW_PASSWORD: "${{ secrets.KUBEFLOW_PASSWORD }}"
      run: |
        python kubeflow/pipelines/main.py