name: Deploy webhook server

permissions:
  id-token: write
  contents: read

on: workflow_dispatch

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  CLUSTER_NAME: "mlops-cluster"
  RESOURCE_GROUP: "mlops"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: OIDC Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Set kubectl context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}
        
    - name: Create ConfigMap with webhook server code
      run: |
        kubectl create configmap webhook-server-code --from-file=monitoring/grafana/webhook-server/webhook-server.py -n monitoring --dry-run=client -o yaml | kubectl apply -f -

    - name: Create ConfigMap with requirements
      run: |
        kubectl create configmap webhook-server-requirements --from-file=monitoring/grafana/webhook-server/requirements.txt -n monitoring --dry-run=client -o yaml | kubectl apply -f -
    
    - name: Create ConfigMap with kfp
      run: |
        kubectl create configmap mlops-pipeline --from-file=kubeflow/kfp/forecasting_pipeline.yaml -n monitoring --dry-run=client -o yaml | kubectl apply -f -
        
    - name: Apply webhook server deployment
      run: |
        kubectl apply -f monitoring/grafana/webhook-server/deployment.yaml -n monitoring

    - name: Create ClusterRoleBinding for webhook server
      run: |
        kubectl create clusterrolebinding kubeflow-edit --clusterrole kubeflow-edit --user system:serviceaccount:monitoring:default
